// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMcKNCL74CQNehaQ6SqTn3SzsO1JUC1lY',
    appId: '1:863046231842:web:5f93871dccd48538dd677b',
    messagingSenderId: '863046231842',
    projectId: 'neohome-iot',
    authDomain: 'neohome-iot.firebaseapp.com',
    storageBucket: 'neohome-iot.firebasestorage.app',
    measurementId: 'G-KSVM52JRRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP518myFN0oVNQrjdLoLccvmUN9B7Nf1Q',
    appId: '1:863046231842:android:4bb0244860d99103dd677b',
    messagingSenderId: '863046231842',
    projectId: 'neohome-iot',
    storageBucket: 'neohome-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOTY4LqdNaPkCTDTvTY8WifX8T9IE6d98',
    appId: '1:863046231842:ios:267499ac1fcb3df9dd677b',
    messagingSenderId: '863046231842',
    projectId: 'neohome-iot',
    storageBucket: 'neohome-iot.firebasestorage.app',
    iosClientId: '863046231842-p3jai8g5thcst4liu518dc7mkofgr8vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.neohomeIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOTY4LqdNaPkCTDTvTY8WifX8T9IE6d98',
    appId: '1:863046231842:ios:267499ac1fcb3df9dd677b',
    messagingSenderId: '863046231842',
    projectId: 'neohome-iot',
    storageBucket: 'neohome-iot.firebasestorage.app',
    iosClientId: '863046231842-p3jai8g5thcst4liu518dc7mkofgr8vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.neohomeIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMcKNCL74CQNehaQ6SqTn3SzsO1JUC1lY',
    appId: '1:863046231842:web:9ad1749caf399724dd677b',
    messagingSenderId: '863046231842',
    projectId: 'neohome-iot',
    authDomain: 'neohome-iot.firebaseapp.com',
    storageBucket: 'neohome-iot.firebasestorage.app',
    measurementId: 'G-X16CYSLCS7',
  );
}
