// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH94iL3Nz2bQ36hB0Pf5GvQQaeOW0xcoI',
    appId: '1:667745206672:web:e920f4967a192b8ffc3315',
    messagingSenderId: '667745206672',
    projectId: 'plastic-51b97',
    authDomain: 'plastic-51b97.firebaseapp.com',
    storageBucket: 'plastic-51b97.firebasestorage.app',
    measurementId: 'G-7BFV19G5E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJGni-k6aWbNMq_Wp07irIPJ45iuhbCZA',
    appId: '1:667745206672:android:89ccb28bc95d0bb6fc3315',
    messagingSenderId: '667745206672',
    projectId: 'plastic-51b97',
    storageBucket: 'plastic-51b97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbCSxP0fRgS7B6Lt6T1I_4P3t9HpUuL6c',
    appId: '1:667745206672:ios:3f10a3f830628852fc3315',
    messagingSenderId: '667745206672',
    projectId: 'plastic-51b97',
    storageBucket: 'plastic-51b97.firebasestorage.app',
    iosBundleId: 'com.example.plastic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbCSxP0fRgS7B6Lt6T1I_4P3t9HpUuL6c',
    appId: '1:667745206672:ios:3f10a3f830628852fc3315',
    messagingSenderId: '667745206672',
    projectId: 'plastic-51b97',
    storageBucket: 'plastic-51b97.firebasestorage.app',
    iosBundleId: 'com.example.plastic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH94iL3Nz2bQ36hB0Pf5GvQQaeOW0xcoI',
    appId: '1:667745206672:web:16b08b390a0135f5fc3315',
    messagingSenderId: '667745206672',
    projectId: 'plastic-51b97',
    authDomain: 'plastic-51b97.firebaseapp.com',
    storageBucket: 'plastic-51b97.firebasestorage.app',
    measurementId: 'G-RMFLGYWNMB',
  );
}
